// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPxmAQtH9bVbxOBJDs7X4mo_hTxBhX1_o',
    appId: '1:47911556093:android:d298a0b5bb824836223f94',
    messagingSenderId: '47911556093',
    projectId: 'gdsc-atmiya',
    storageBucket: 'gdsc-atmiya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzSxXUi5IO-xD_iviQsdlONjI8YmbfFkw',
    appId: '1:47911556093:ios:f7b2075954395f2e223f94',
    messagingSenderId: '47911556093',
    projectId: 'gdsc-atmiya',
    storageBucket: 'gdsc-atmiya.appspot.com',
    androidClientId: '47911556093-drte0ll3l70jksbksc5vgs0oadclnk4d.apps.googleusercontent.com',
    iosClientId: '47911556093-1koorjuk4fsqfs68aiuv353bm2oj50g6.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdscAtmiya',
  );
}
